Add python3 support
trevormccasland/jenkins2sql pull request #3
Opened 2018-10-12 06:28 UTC by stannum-l

This patch set adds python 3.5 and 3.6 support to the repository, as py27 is
scheduled to be EOL in 2020. This also updates Travis to perform CI
operations on py35 and py36.

Signed-off-by: Tin Lam <tin@irrational.io>

2018-10-19 17:20 UTC, trevormccasland requested changes
Can you update the setup.cfg file to put the py3 support in the package install information? Thanks
https://github.com/trevormccasland/jenkins2sql/blob/master/setup.cfg#L17

2018-10-20 14:14 UTC, stannum-l commented
Done.

2018-10-22 02:02 UTC, merged

2018-10-22 02:06 UTC, trevormccasland commented
I can't seem to merge the branch with the repository in its current condition.

2018-10-22 02:06 UTC, trevormccasland commented
I can't seem to merge the branch with the repository in its current condition.

2018-10-22 04:19 UTC, stannum-l commented
weird - but then it said it merged.  Thanks.